[app]
port=3000
name="db2rest"
debug=true
env="dev"
site_url='http://localhost:1113' #网站地址

[[services]]
name="任务"
server_url= 'http://localhost:8080/server_url' #接口地址
proxy_uri="/server_url"

[pkg]
url="http://localhost:8080/pkg"
token=""
